name: 'Auto Ticket link commenter'
description: 'Comments JIRA ticket link in pull request'
inputs:
  jira-project-url:
    description: 'Link of your project URL'
    required: true
  GITHUB_TOKEN:
    description: 'Add token'
    required: true
  custom-comment:
    description: 'Add custom comment'
    default: 'Thank you for your contribution! :confetti_ball:'
    required: false
  ticket-regex-title:
    description: 'Use custom regex to pick ticket name'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'anchor'
  color: 'blue'
